spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/face?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: main0126
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.usedbook.pojo
  configuration:
    map-underscore-to-camel-case: true
img-file-path:
  win-path: F://2022.4.12二手书城项目//imgs
  linux-path: /usr/local/img/


server:
  port: 8843
